### ISSUE TITLE
Does this have an impact on manual cars? 

### ISSUE THREAD

**Issue by zarboz** [kmalinich/node-bmw-client#20]
https://github.com/kmalinich/node-bmw-client/blob/ebd48e5350e5fae7c336c25db92b4785942de655/lib/config-default.js#L64

I understand the concept of what happens with these values but do they impact a manual car?

**Comment by kmalinich** [comment]
No, I originally populated that object in the config because I was going to build a dynamic rev-matching calculator on clutch in, but I haven't gotten around to it yet. Those values are from a Getdrag 420G used on the BMW E39 540i ( https://en.wikipedia.org/wiki/Getrag_420G_transmission )
